CREATE DATABASE ATENDIMENTOS;

USE ATENDIMENTOS;

CREATE TABLE ATD_MEDICO(

MED_CRM VARCHAR(10) NOT NULL ,
MED_NOME VARCHAR(60) NOT NULL,
MED_FONE VARCHAR(15),
CONSTRAINT MED_PK PRIMARY KEY (MED_CRM)
);

CREATE TABLE ATD_PACIENTE(
PAC_CODIGO INTEGER NOT NULL,
PAC_NOME VARCHAR(60) NOT NULL,
PAC_FONE VARCHAR(15) NOT NULL,
ATE_ENDERECO VARCHAR(100)NOT NULL,
CONSTRAINT PAC_PK PRIMARY KEY (PAC_CODIGO)
);

CREATE TABLE ATD_ATENDIMENTOS(
ATE_CODIGO INTEGER NOT NULL,
ATE_DATA_HORA DATETIME NOT NULL,
ATE_MED_CRM VARCHAR(10) NOT NULL,
ATE_PAC_CODIGO INTEGER NOT NULL,
CONSTRAINT ATE_PK PRIMARY KEY (ATE_CODIGO),
CONSTRAINT MED_FK FOREIGN KEY (ATE_MED_CRM) REFERENCES ATD_MEDICO(MED_CRM),
CONSTRAINT PAC_FK FOREIGN KEY (ATE_PAC_CODIGO) REFERENCES ATD_PACIENTE(PAC_CODIGO)
);

ALTER TABLE ATD_MEDICO ADD MED_EMAIL VARCHAR(100);
ALTER TABLE ATD_PACIENTE ADD PAC_ENDRECO VARCHAR(100);
ALTER TABLE ATD_ATENDIMENTOS ADD ATE_STATUS VARCHAR(55) NOT NULL default ('N');
ALTER TABLE ATD_ATENDIMENTOS ADD CONSTRAINT ck_ATD CHECK (ATD IN (‘A’,’E’,’N’)); 

